# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish package
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Increment version
      id: increment-version
      uses: RichardInnocent/semantic-versioning-maven@v0.1.0
    - name: Print if version changed
      if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
      run: echo "The new version is now $new_version"
      env:
        new_version: ${{ steps.increment-version.outputs.new-version }}
    - name: Publish package
      if: steps.bump.outputs.bumped == false
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
