name: TEst

on: workflow_dispatch

jobs:
  check_vars:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        env:
          uploadTrack: ${{ startsWith(github.ref, 'refs/tags/production-') && 'production' || 'qa' }}
        run: |
          echo "$Greeting $uploadTrack"
          echo "VERCEL_TARGET=$uploadTrack" >> "$GITHUB_ENV"
      - name: "Say Hello again"
        run: echo "$Greeting VERCEL_TARGET $VERCEL_TARGET"
