name: Publish package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Increment version
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "current version $CURRENT_VERSION"
        if echo $CURRENT_VERSION | grep -iq "-SNAPSHOT"; then
          LOWERCASE=${CURRENT_VERSION,,}
          NEW_VERSION="${LOWERCASE/-snapshot/}"
          echo $NEW_VERSION
        else
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 | cut -d- -f1)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        fi
        # Update version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
    - name: Publish package
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Increment version
      run: |
        # Extract current version and increment patch version
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 | cut -d- -f1)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH-SNAPSHOT"

        # Update version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
        # Commit and push the new snapshot version
#        git add pom.xml
#        git commit -m "Increment version to $NEW_VERSION"
#        git push origin $(git rev-parse --abbrev-ref HEAD)
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Update version"
