name: Publish package
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: increment version
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "current version $CURRENT_VERSION"
        if echo $CURRENT_VERSION | grep -iq "\-SNAPSHOT"; then
          LOWERCASE=${CURRENT_VERSION,,}
          NEW_VERSION="${LOWERCASE/-snapshot/}"
        else
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 | cut -d- -f1)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        fi
        echo $NEW_VERSION
        mvn -q versions:set -DnewVersion=$NEW_VERSION
        mvn -q versions:commit

        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add pom.xml
        git commit -m "Increment version to $NEW_VERSION"
        git tag "v$NEW_VERSION"
    - name: publish package
      run: mvn -q deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: update version to snapshot
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3 | cut -d- -f1)
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH-SNAPSHOT"
        echo $NEW_VERSION

        # update version in pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit

        # commit
        git add pom.xml
        git commit -m "Update version to $NEW_VERSION"
#        git push origin $(git rev-parse --abbrev-ref HEAD)
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
