name: Publish package
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}
    - name: Print version & publish
      run: "echo 'New Version: ${{ steps.bump.outputs.version }} '" & mvn deploy
        GITHUB_TOKEN: ${{ github.token }}
